# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-12 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='标签'),
        ),
    ]
