# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-19 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0002_auto_20180312_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='正文')),
                ('date', models.DateField(auto_now=True, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': '时事热点',
                'verbose_name_plural': '时事热点',
            },
        ),
    ]
