# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0003_hotspot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '错题标签', 'verbose_name_plural': '错题标签'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='错题标签'),
        ),
    ]
