# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0004_auto_20180327_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonWeaknessCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('math', '数学'), ('english', '英语'), ('politic', '政治'), ('major', '专业课')], max_length=10, unique=True, verbose_name='弱项分类')),
            ],
            options={
                'verbose_name': '公共弱点分类',
                'verbose_name_plural': '公共弱点分类',
            },
        ),
        migrations.CreateModel(
            name='CommonWeaknessTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=20, null=True, unique=True, verbose_name='弱项标签')),
                ('category_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_platform.CommonWeaknessCategory', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '公共弱项标签',
                'verbose_name_plural': '公共弱项标签',
            },
        ),
    ]
