# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0005_commonweaknesscategory_commonweaknesstag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commonweaknesscategory',
            options={'verbose_name': '公共弱项分类', 'verbose_name_plural': '公共弱项分类'},
        ),
        migrations.AlterField(
            model_name='commonweaknesscategory',
            name='name',
            field=models.CharField(max_length=10, unique=True, verbose_name='弱项分类'),
        ),
    ]
