# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-02 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0006_auto_20180327_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='score',
            field=models.IntegerField(default=1, verbose_name='错题标签的评分'),
        ),
    ]
