# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-04 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0007_tag_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main_platform.Tag', verbose_name='标签'),
            preserve_default=False,
        ),
    ]
