# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-10 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='邮箱'),
        ),
    ]
