# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-13 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180310_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='present_university',
            new_name='presentCollege',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='goal_university',
            new_name='targetCollege',
        ),
    ]
