# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-22 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180313_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lastCheckinDate',
            field=models.DateField(blank=True, null=True, verbose_name='上次打卡日期'),
        ),
    ]
