# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-22 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_lastcheckindate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='memo',
            field=models.TextField(default='', max_length=200, verbose_name='备忘录'),
        ),
    ]
