# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-22 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermemo',
            name='user_belong',
        ),
        migrations.DeleteModel(
            name='UserMemo',
        ),
    ]
