# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 00:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180322_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaknessCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('math', '数学'), ('english', '英语'), ('politic', '政治'), ('major', '专业课')], max_length=10, unique=True, verbose_name='弱项分类')),
                ('user_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '弱项分类',
                'verbose_name_plural': '弱项分类',
            },
        ),
        migrations.CreateModel(
            name='WeaknessTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=20, null=True, unique=True, verbose_name='弱项标签')),
                ('category_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.WeaknessCategory', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '弱项标签',
                'verbose_name_plural': '弱项标签',
            },
        ),
    ]
