# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_weaknesscategory_weaknesstag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeaknessCategory',
            new_name='UserWeaknessCategory',
        ),
        migrations.RenameModel(
            old_name='WeaknessTag',
            new_name='UserWeaknessTag',
        ),
    ]
