# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180327_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userweaknesscategory',
            name='name',
            field=models.CharField(max_length=10, unique=True, verbose_name='弱项分类'),
        ),
    ]
