# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180327_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userweaknesscategory',
            name='name',
            field=models.CharField(max_length=10, verbose_name='弱项分类'),
        ),
        migrations.AlterField(
            model_name='userweaknesstag',
            name='name',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='弱项标签'),
        ),
    ]
